
train:
  - class_name: albumentations.RandomRotate90
    params:
      p: 1
  - class_name: albumentations.ColorJitter
    params:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.2
      p: 0.8
  - class_name: albumentations.CLAHE
    params:
      clip_limit: 4.0
      p: 0.8  
  - class_name: albumentations.Normalize
    params:
      p: 1.0
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
  - class_name: albumentations.Resize
    params:
      height: 512
      width: 512
  - class_name: albumentations.pytorch.transforms.ToTensorV2
    params:
      p: 1.0
test:
  - class_name: albumentations.Normalize
    params:
      p: 1.0
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
  - class_name: albumentations.Resize
    params:
      height: 512
      width: 512
  - class_name: albumentations.pytorch.transforms.ToTensorV2
    params:
        p: 1.0