
train:
  - class_name: albumentations.Flip
    params:
      p: 1
  - class_name: albumentations.RandomRotate90
    params:
      p: 1
  - class_name: albumentations.ElasticTransform
    params:
      p: 1
      alpha: 120
      sigma: 6
      alpha_affine: 3.6
  - class_name: albumentations.Resize
    params:
      height: 512
      width: 512
  - class_name: albumentations.Normalize
    params:
      p: 1.0
  - class_name: albumentations.pytorch.transforms.ToTensorV2
    params:
      p: 1.0
test:
  - class_name: albumentations.Resize
    params:
      height: 512
      width: 512
  - class_name: albumentations.Normalize
    params:
        p: 1.0
  - class_name: albumentations.pytorch.transforms.ToTensorV2
    params:
        p: 1.0