defaults:
  - _self_
  - callbacks: callbacks
  - private: default
  - datamodule: hotdog
  - logging: wandb
  - loss: bce_logits
  - metric: accuracy
  - model: resnet18_transfer
  - optimizer: adam
  - scheduler: cosine
  - trainer: default_trainer
  - training: default_training
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  run_name: run
  logs_folder_name: logs
  workspace: computervision02514
  project_name: DL4CV
  device: gpu
  log_code: False
  save_pytorch_model: True
  save_best: True
  convert_to_jit: True
  predict: True

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    #subdir: ${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}_${datamodule.fold_n}
