datamodule_name: dl4cv.lightning_classes.SegmentDataModule
params:
  builder: dl4cv.datasets.build_ph2
  path: /dtu/datasets1/02514/PH2_Dataset_images
  split: [150, 25]
  batch_size: 6
  num_workers: 4
  pin_memory: True
