# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.dev12+g25f4309.d20230603"
__version_tuple__ = version_tuple = (0, 1, "dev12", "g25f4309.d20230603")
