
log: True
loggers:
  - class_name: pytorch_lightning.loggers.CSVLogger
    params:
      save_dir: logs/csv_log.csv
#      name: ${general.run_name}
      name: .
  #    - class_name: src.utils.loggers.PrintLogger
  #      params:
  #        csv_path:

  - class_name: pytorch_lightning.loggers.TensorBoardLogger
    params:
      save_dir: ${general.logs_folder_name}
      name: ${general.run_name}

  - class_name: pytorch_lightning.loggers.WandbLogger
    params:
      save_dir: ${general.logs_folder_name}
      entity: ${general.workspace}
      #workspace: ${general.workspace}
      project: ${general.project_name}
      #api_key: ${private.wandb_api_key}
      name: ${general.run_name}

